# docker run --rm -it tensorflow/tensorflow bash
# python --version
# pip list | grep tensorflow
# pip freeze
#      - keras==3.6.0
#      - tensorboard==2.18.0
#      - tensorboard-data-server==0.7.2
#      - tensorflow-io-gcs-filesystem==0.37.1
#      - tensorflow_cpu==2.18.0

name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Replace with the correct version
  - pip
  - numpy
  - pandas
  - matplotlib
  - tensorflow
  - scikit-learn==1.5.2
  - scikeras
  - ta
  - matplotlib-inline
  - ipython
  - jupyter
  - ta-lib
