name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # Tensorflow only supports Python 3.8 to 3.11 ( in feb 14 2025 ) My code works in 3.8
  - numpy
  - pandas
  - tensorflow  # Or tensorflow-cpu if needed
  - scikit-learn
