# docker run --rm -it tensorflow/tensorflow bash
# python --version
# pip list | grep tensorflow
# pip freeze

name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Replace with the correct version
  - pip
  - pip:
      - tensorflow==2.18.0  # Replace with extracted version
      - absl-py==2.1.0
      - astunparse==1.6.3
      - blinker==1.4
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - cryptography==3.4.8
      - dbus-python==1.2.18
      - distro==1.7.0
      - flatbuffers==24.3.25
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.67.0
      - h5py==3.12.1
      - httplib2==0.20.2
      - idna==3.10
      - importlib-metadata==4.6.4
      - jeepney==0.7.1
      - keras==3.6.0
      - keyring==23.5.0
      - launchpadlib==1.10.16
      - lazr.restfulclient==0.14.4
      - lazr.uri==1.0.6
      - libclang==18.1.1
      - Markdown==3.7
      - markdown-it-py==3.0.0
      - MarkupSafe==3.0.2
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - more-itertools==8.10.0
      - namex==0.0.8
      - numpy==2.0.2
      - oauthlib==3.2.0
      - opt_einsum==3.4.0
      - optree==0.13.0
      - packaging==24.1
      - protobuf==5.28.3
      - Pygments==2.18.0
      - PyGObject==3.42.1
      - PyJWT==2.3.0
      - pyparsing==2.4.7
      - python-apt==2.4.0+ubuntu4
      - requests==2.32.3
      - rich==13.9.3
      - SecretStorage==3.3.1
      - six==1.16.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow_cpu==2.18.0
      - termcolor==2.5.0
      - typing_extensions==4.12.2
      - urllib3==2.2.3
      - wadllib==1.3.6
      - Werkzeug==3.0.5
      - wrapt==1.16.0
      - zipp==1.0.0
